channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - accelerate>=0.33.0
  - datasets~=2.21.0
  - fastai~=2.7.17
  - gensim>=4.3.2
  - ipywidgets>=8.1.5
  - jupyter-lsp-python>=2.2.5
  - jupyterlab~=4.2.5
  - kaggle>=1.6.17
  - lightning
  - lxml>=4.9.3
  - matplotlib-base~=3.9.2
  - nbconvert>=7.16.4
  - nltk~=3.9.1
  - numexpr~=2.8.7
  - numpy~=1.26.4
  - openai~=1.43.0
  - pandas~=2.2.2
  - plotly~=5.24.0
  - protobuf>=4.25.3
  - python-graphviz>=0.20.3
  - python>3.11.0
  - pytorch
  - scikit-learn
  - scipy~=1.14.1
  - seaborn~=0.13.2
  - sentencepiece>=0.2.0
  - timm>=1.0.9
  - tokenizers~=0.19.1
  - torchaudio~=2.4.0
  - torchvision~=0.19.0
  - transformers~=4.44.2
  - pip:
    - svgling>=0.5.0
